version: 1.0

linter: jetbrains/qodana-python:latest

profile:
  name: qodana.recommended

exclude:
  - name: All
    paths:
      - .git/
      - .github/
      - venv/
      - .venv/
      - __pycache__/
      - .pytest_cache/

include:
  - name: CheckDependencyLicenses
  - name: PyUnresolvedReferences
  - name: PyUnusedLocal
  - name: PyPep8Naming
  - name: PyShadowingNames
  - name: PyRedeclaration
  - name: PyMethodMayBeStatic
  - name: PyCompatibility
  - name: PyBroadException

failThreshold: 10

bootstrap: |
  pip install -r requirements.txt
